exclude: README.md
repos:
  - repo: https://github.com/ambv/black
    rev: '22.12.0'
    hooks:
      - id: black
        args: ['--quiet']
  - repo: https://github.com/pycqa/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args: ['--recursive', '--expand-star-imports', '--remove-all-unused-imports', '--in-place', '--ignore-init-module-imports']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear==20.1.4',  # Looks for likely bugs and design problems
          'flake8-comprehensions==3.2.3',  # Looks for unnecessary generator functions that can be converted to list comprehensions
          'flake8-deprecated==1.3',  # Looks for method deprecations
          'flake8-use-fstring==1.1',  # Enforces use of f-strings over .format and %s
          'flake8-print==3.1.4',  # Checks for print statements
          'flake8-docstrings==1.5.0',  # Verifies that all functions/methods have docstrings
          'flake8-type-annotations==0.1.0',  # Looks for misconfigured type annotations
          'flake8-annotations==2.4.0',  # Enforces type annotation
          'pep8-naming', # PEP 8 Naming Conventions
        ]
        args: ['--enable-extensions=G']
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ["--py37-plus", "--keep-runtime-typing"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
