[tool.poetry]
name = "llm-fun"
version = "0.1.0"
description = ""
authors = ["astew"]
readme = "README.md"
packages = [{include = "llm_fun"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
